set(SYSTEM_FILES
    src/sysBootup.cpp
    # sysDolphin
    src/sysDolphin/controllerMgr.cpp
    src/sysDolphin/dgxGraphics.cpp
    src/sysDolphin/gameApp.cpp
    src/sysDolphin/sysNew.cpp
    src/sysDolphin/system.cpp
    src/sysDolphin/texture.cpp
    # sysCommon
    src/sysCommon/atx.cpp
    src/sysCommon/ayuStack.cpp
    src/sysCommon/baseApp.cpp
    src/sysCommon/camera.cpp
    src/sysCommon/cmdStream.cpp
    src/sysCommon/controller.cpp
    src/sysCommon/graphics.cpp
    src/sysCommon/grLight.cpp
    src/sysCommon/id32.cpp
    src/sysCommon/matMath.cpp
    src/sysCommon/node.cpp
    src/sysCommon/shapeBase.cpp
    src/sysCommon/shpLightFlares.cpp
    src/sysCommon/shpObjColl.cpp
    src/sysCommon/shpRoutes.cpp
    src/sysCommon/stdSystem.cpp
    src/sysCommon/stream.cpp
    src/sysCommon/streamBufferedInput.cpp
    src/sysCommon/string.cpp
    src/sysCommon/sysMath.cpp
    src/sysCommon/timers.cpp
    # hvqm4dec
    src/hvqm4dec/hvqm4dec.c
)

set(JAUDIO_FILES
    src/jaudio/aictrl.c
    src/jaudio/app_inter.c
    src/jaudio/aramcall.c
    src/jaudio/audiomesg.c
    src/jaudio/audiothread.c
    src/jaudio/bankdrv.c
    src/jaudio/bankloader.c
    src/jaudio/bankread.c
    src/jaudio/centcalc.c
    src/jaudio/cmdqueue.c
    src/jaudio/cmdstack.c
    src/jaudio/connect.c
    src/jaudio/cpubuf.c
    src/jaudio/driverinterface.c
    src/jaudio/dsp_cardunlock.c
    src/jaudio/dspboot.c
    src/jaudio/dspbuf.c
    src/jaudio/dspdriver.c
    src/jaudio/dspinterface.c
    src/jaudio/dspproc.c
    src/jaudio/dsptask.c
    src/jaudio/dummyprobe.c
    src/jaudio/dummyrom.c
    src/jaudio/dvdthread.c
    src/jaudio/fat.c
    src/jaudio/file_seq.c
    src/jaudio/filter3d.c
    src/jaudio/fxinterface.c
    src/jaudio/heapctrl.c
    src/jaudio/hvqm_play.c
    src/jaudio/interface.c
    src/jaudio/interleave.c
    src/jaudio/ipldec.c
    src/jaudio/ja_calc.c
    src/jaudio/jammain_2.c
    src/jaudio/jamosc.c
    src/jaudio/memory.c
    src/jaudio/midplay.c
    src/jaudio/noteon.c
    src/jaudio/oneshot.c
    src/jaudio/osdsp_task.c
    src/jaudio/osdsp.c
    src/jaudio/piki_bgm.c
    src/jaudio/piki_player.c
    src/jaudio/piki_scene.c
    src/jaudio/pikidemo.c
    src/jaudio/pikiinter.c
    src/jaudio/pikiseq.c
    src/jaudio/playercall.c
    src/jaudio/random.c
    src/jaudio/rate.c
    src/jaudio/sample.c
    src/jaudio/seqsetup.c
    src/jaudio/stackchecker.c
    src/jaudio/streamctrl.c
    src/jaudio/syncstream.c
    src/jaudio/tables.c
    src/jaudio/verysimple.c
    src/jaudio/virload.c
    src/jaudio/waveread.c
)

set(DOLPIK_FILES
    # plugPikiColin
    src/plugPikiColin/plugPiki.cpp
    src/plugPikiColin/animMgr.cpp
    src/plugPikiColin/cardSelect.cpp
    src/plugPikiColin/cardutil.cpp
    src/plugPikiColin/cinePlayer.cpp
    src/plugPikiColin/dayMgr.cpp
    src/plugPikiColin/dynsimulator.cpp
    src/plugPikiColin/game.cpp
    src/plugPikiColin/gameExit.cpp
    src/plugPikiColin/gameflow.cpp
    src/plugPikiColin/gamePrefs.cpp
    src/plugPikiColin/gameSetup.cpp
    src/plugPikiColin/gauges.cpp
    src/plugPikiColin/genMapObject.cpp
    src/plugPikiColin/gui.cpp
    src/plugPikiColin/introGame.cpp
    src/plugPikiColin/lightPool.cpp
    src/plugPikiColin/mapMgr.cpp
    src/plugPikiColin/mapSelect.cpp
    src/plugPikiColin/memoryCard.cpp
    src/plugPikiColin/moviePlayer.cpp
    src/plugPikiColin/movSample.cpp
    src/plugPikiColin/newPikiGame.cpp
    src/plugPikiColin/ninLogo.cpp
    src/plugPikiColin/parameters.cpp
    src/plugPikiColin/titles.cpp
    # plugPikiKando
    src/plugPikiKando/actor.cpp
    src/plugPikiKando/actorMgr.cpp
    src/plugPikiKando/aiAction.cpp
    src/plugPikiKando/aiActions.cpp
    src/plugPikiKando/aiAttack.cpp
    src/plugPikiKando/aiBoMake.cpp
    src/plugPikiKando/aiBore.cpp
    src/plugPikiKando/aiBou.cpp
    src/plugPikiKando/aiBreakWall.cpp
    src/plugPikiKando/aiBridge.cpp
    src/plugPikiKando/aiChase.cpp
    src/plugPikiKando/aiConstants.cpp
    src/plugPikiKando/aiCrowd.cpp
    src/plugPikiKando/aiDecoy.cpp
    src/plugPikiKando/aiEnter.cpp
    src/plugPikiKando/aiEscape.cpp
    src/plugPikiKando/aiExit.cpp
    src/plugPikiKando/aiFormation.cpp
    src/plugPikiKando/aiFree.cpp
    src/plugPikiKando/aiGoto.cpp
    src/plugPikiKando/aiGuard.cpp
    src/plugPikiKando/aiKinoko.cpp
    src/plugPikiKando/aiMine.cpp
    src/plugPikiKando/aiPerf.cpp
    src/plugPikiKando/aiPick.cpp
    src/plugPikiKando/aiPickCreature.cpp
    src/plugPikiKando/aiPullout.cpp
    src/plugPikiKando/aiPush.cpp
    src/plugPikiKando/aiPut.cpp
    src/plugPikiKando/aiRandomBoid.cpp
    src/plugPikiKando/aiRescue.cpp
    src/plugPikiKando/aiRope.cpp
    src/plugPikiKando/aiShoot.cpp
    src/plugPikiKando/aiStone.cpp
    src/plugPikiKando/aiTable.cpp
    src/plugPikiKando/aiTransport.cpp
    src/plugPikiKando/aiWatch.cpp
    src/plugPikiKando/aiWeed.cpp
    src/plugPikiKando/animPellet.cpp
    src/plugPikiKando/bombItem.cpp
    src/plugPikiKando/bugprint.cpp
    src/plugPikiKando/collInfo.cpp
    src/plugPikiKando/complexCreature.cpp
    src/plugPikiKando/conditions.cpp
    src/plugPikiKando/courseDebug.cpp
    src/plugPikiKando/cPlate.cpp
    src/plugPikiKando/creature.cpp
    src/plugPikiKando/creatureCollision.cpp
    src/plugPikiKando/creatureCollPart.cpp
    src/plugPikiKando/creatureMove.cpp
    src/plugPikiKando/creatureStick.cpp
    src/plugPikiKando/demoEvent.cpp
    src/plugPikiKando/demoInvoker.cpp
    src/plugPikiKando/dualCreature.cpp
    src/plugPikiKando/dynCreature.cpp
    src/plugPikiKando/eventListener.cpp
    src/plugPikiKando/fastGrid.cpp
    src/plugPikiKando/fishItem.cpp
    src/plugPikiKando/formationMgr.cpp
    src/plugPikiKando/gameCoreSection.cpp
    src/plugPikiKando/gameDemo.cpp
    src/plugPikiKando/gameStat.cpp
    src/plugPikiKando/genActor.cpp
    src/plugPikiKando/generator.cpp
    src/plugPikiKando/generatorCache.cpp
    src/plugPikiKando/genItem.cpp
    src/plugPikiKando/genMapParts.cpp
    src/plugPikiKando/genNavi.cpp
    src/plugPikiKando/genPellet.cpp
    src/plugPikiKando/globalShapes.cpp
    src/plugPikiKando/gmWin.cpp
    src/plugPikiKando/goalItem.cpp
    src/plugPikiKando/interactBattle.cpp
    src/plugPikiKando/interactEtc.cpp
    src/plugPikiKando/interactGrab.cpp
    src/plugPikiKando/interactPullout.cpp
    src/plugPikiKando/itemAI.cpp
    src/plugPikiKando/itemGem.cpp
    src/plugPikiKando/itemMgr.cpp
    src/plugPikiKando/itemObject.cpp
    src/plugPikiKando/keyConfig.cpp
    src/plugPikiKando/keyItem.cpp
    src/plugPikiKando/kio.cpp
    src/plugPikiKando/kmath.cpp
    src/plugPikiKando/kontroller.cpp
    src/plugPikiKando/kusaItem.cpp
    src/plugPikiKando/mapcode.cpp
    src/plugPikiKando/mapParts.cpp
    src/plugPikiKando/memStat.cpp
    src/plugPikiKando/mizuItem.cpp
    src/plugPikiKando/navi.cpp
    src/plugPikiKando/naviDemoState.cpp
    src/plugPikiKando/naviMgr.cpp
    src/plugPikiKando/naviState.cpp
    src/plugPikiKando/objectMgr.cpp
    src/plugPikiKando/objectTypes.cpp
    src/plugPikiKando/odoMeter.cpp
    src/plugPikiKando/omake.cpp
    src/plugPikiKando/paniItemAnimator.cpp
    src/plugPikiKando/panipikianimator.cpp
    src/plugPikiKando/paniPlantAnimator.cpp
    src/plugPikiKando/pelletMgr.cpp
    src/plugPikiKando/pelletState.cpp
    src/plugPikiKando/piki.cpp
    src/plugPikiKando/pikidoKill.cpp
    src/plugPikiKando/pikiheadItem.cpp
    src/plugPikiKando/pikiInf.cpp
    src/plugPikiKando/pikiInfo.cpp
    src/plugPikiKando/pikiMgr.cpp
    src/plugPikiKando/pikiState.cpp
    src/plugPikiKando/plantMgr.cpp
    src/plugPikiKando/playerState.cpp
    src/plugPikiKando/radarInfo.cpp
    src/plugPikiKando/resultFlag.cpp
    src/plugPikiKando/ropeCreature.cpp
    src/plugPikiKando/ropeItem.cpp
    src/plugPikiKando/routeMgr.cpp
    src/plugPikiKando/saiEvents.cpp
    src/plugPikiKando/searchSystem.cpp
    src/plugPikiKando/seConstants.cpp
    src/plugPikiKando/seedItem.cpp
    src/plugPikiKando/seMgr.cpp
    src/plugPikiKando/simpleAI.cpp
    src/plugPikiKando/smartPtr.cpp
    src/plugPikiKando/soundMgr.cpp
    src/plugPikiKando/ufoAnim.cpp
    src/plugPikiKando/ufoItem.cpp
    src/plugPikiKando/updateMgr.cpp
    src/plugPikiKando/uteffect.cpp
    src/plugPikiKando/utkando.cpp
    src/plugPikiKando/viewPiki.cpp
    src/plugPikiKando/weedsItem.cpp
    src/plugPikiKando/workObject.cpp
    # plugPikiNakata
    src/plugPikiNakata/genteki.cpp
    src/plugPikiNakata/nakatacode.cpp
    src/plugPikiNakata/nlibfunction.cpp
    src/plugPikiNakata/nlibgeometry.cpp
    src/plugPikiNakata/nlibgeometry3d.cpp
    src/plugPikiNakata/nlibgraphics.cpp
    src/plugPikiNakata/nlibmath.cpp
    src/plugPikiNakata/nlibspline.cpp
    src/plugPikiNakata/nlibsystem.cpp
    src/plugPikiNakata/panianimator.cpp
    src/plugPikiNakata/panipikianimmgr.cpp
    src/plugPikiNakata/panitekianimator.cpp
    src/plugPikiNakata/panitestsection.cpp
    src/plugPikiNakata/paraparameters.cpp
    src/plugPikiNakata/pcamcamera.cpp
    src/plugPikiNakata/pcamcameramanager.cpp
    src/plugPikiNakata/pcamcameraparameters.cpp
    src/plugPikiNakata/pcammotionevents.cpp
    src/plugPikiNakata/peve.cpp
    src/plugPikiNakata/peveconditions.cpp
    src/plugPikiNakata/pevemotionevents.cpp
    src/plugPikiNakata/tai.cpp
    src/plugPikiNakata/taiattackactions.cpp
    src/plugPikiNakata/taibasicactions.cpp
    src/plugPikiNakata/taichappy.cpp
    src/plugPikiNakata/taicollec.cpp
    src/plugPikiNakata/taicollisionactions.cpp
    src/plugPikiNakata/taieffectactions.cpp
    src/plugPikiNakata/taiiwagen.cpp
    src/plugPikiNakata/taijudgementactions.cpp
    src/plugPikiNakata/taikinoko.cpp
    src/plugPikiNakata/taimessageactions.cpp
    src/plugPikiNakata/taimizinko.cpp
    src/plugPikiNakata/taimotionactions.cpp
    src/plugPikiNakata/taimoveactions.cpp
    src/plugPikiNakata/tainapkid.cpp
    src/plugPikiNakata/taiotimoti.cpp
    src/plugPikiNakata/taipalm.cpp
    src/plugPikiNakata/taireactionactions.cpp
    src/plugPikiNakata/taiwaitactions.cpp
    src/plugPikiNakata/teki.cpp
    src/plugPikiNakata/tekianimationmanager.cpp
    src/plugPikiNakata/tekibteki.cpp
    src/plugPikiNakata/tekiconditions.cpp
    src/plugPikiNakata/tekievent.cpp
    src/plugPikiNakata/tekiinteraction.cpp
    src/plugPikiNakata/tekimgr.cpp
    src/plugPikiNakata/tekinakata.cpp
    src/plugPikiNakata/tekinteki.cpp
    src/plugPikiNakata/tekiparameters.cpp
    src/plugPikiNakata/tekipersonality.cpp
    src/plugPikiNakata/tekistrategy.cpp
    # plugPikiNishimura
    src/plugPikiNishimura/Boss.cpp
    src/plugPikiNishimura/BossAnimMgr.cpp
    src/plugPikiNishimura/BossCnd.cpp
    src/plugPikiNishimura/BossMgr.cpp
    src/plugPikiNishimura/BossShapeObj.cpp
    src/plugPikiNishimura/CoreNucleus.cpp
    src/plugPikiNishimura/CoreNucleusAi.cpp
    src/plugPikiNishimura/genBoss.cpp
    src/plugPikiNishimura/HmRumbleMgr.cpp
    src/plugPikiNishimura/HmRumbleSample.cpp
    src/plugPikiNishimura/King.cpp
    src/plugPikiNishimura/KingAi.cpp
    src/plugPikiNishimura/KingBack.cpp
    src/plugPikiNishimura/KingBody.cpp
    src/plugPikiNishimura/Kogane.cpp
    src/plugPikiNishimura/KoganeAi.cpp
    src/plugPikiNishimura/Mizu.cpp
    src/plugPikiNishimura/MizuAi.cpp
    src/plugPikiNishimura/nscalculation.cpp
    src/plugPikiNishimura/Nucleus.cpp
    src/plugPikiNishimura/NucleusAi.cpp
    src/plugPikiNishimura/Pom.cpp
    src/plugPikiNishimura/PomAi.cpp
    src/plugPikiNishimura/RumbleData.cpp
    src/plugPikiNishimura/Slime.cpp
    src/plugPikiNishimura/SlimeAi.cpp
    src/plugPikiNishimura/SlimeBody.cpp
    src/plugPikiNishimura/SlimeCreature.cpp
    src/plugPikiNishimura/Snake.cpp
    src/plugPikiNishimura/SnakeAi.cpp
    src/plugPikiNishimura/SnakeBody.cpp
    src/plugPikiNishimura/Spider.cpp
    src/plugPikiNishimura/SpiderAi.cpp
    src/plugPikiNishimura/SpiderLeg.cpp
    # plugPikiOgawa
    src/plugPikiOgawa/ogCallBack.cpp
    src/plugPikiOgawa/ogDiary.cpp
    src/plugPikiOgawa/ogFileChkSel.cpp
    src/plugPikiOgawa/ogFileCopy.cpp
    src/plugPikiOgawa/ogFileDelete.cpp
    src/plugPikiOgawa/ogFileSelect.cpp
    src/plugPikiOgawa/ogGraph.cpp
    src/plugPikiOgawa/ogMakeDefault.cpp
    src/plugPikiOgawa/ogMap.cpp
    src/plugPikiOgawa/ogMemChk.cpp
    src/plugPikiOgawa/ogMenu.cpp
    src/plugPikiOgawa/ogMessage.cpp
    src/plugPikiOgawa/ogNitaku.cpp
    src/plugPikiOgawa/ogPause.cpp
    src/plugPikiOgawa/ogRader.cpp
    src/plugPikiOgawa/ogResult.cpp
    src/plugPikiOgawa/ogSave.cpp
    src/plugPikiOgawa/ogStart.cpp
    src/plugPikiOgawa/ogSub.cpp
    src/plugPikiOgawa/ogTest.cpp
    src/plugPikiOgawa/ogTitle.cpp
    src/plugPikiOgawa/ogTotalScore.cpp
    src/plugPikiOgawa/ogTutorial.cpp
    src/plugPikiOgawa/ogTutorialData.cpp
    # plugPikiYamashita
    src/plugPikiYamashita/alphaWipe.cpp
    src/plugPikiYamashita/bBoardColourAnim.cpp
    src/plugPikiYamashita/damageEffect.cpp
    src/plugPikiYamashita/drawAccount.cpp
    src/plugPikiYamashita/drawCMbest.cpp
    src/plugPikiYamashita/drawCMcourseSelect.cpp
    src/plugPikiYamashita/drawCMresult.cpp
    src/plugPikiYamashita/drawCMscore.cpp
    src/plugPikiYamashita/drawCMtitle.cpp
    src/plugPikiYamashita/drawCommon.cpp
    src/plugPikiYamashita/drawContainer.cpp
    src/plugPikiYamashita/drawCountDown.cpp
    src/plugPikiYamashita/drawFinalResult.cpp
    src/plugPikiYamashita/drawGameInfo.cpp
    src/plugPikiYamashita/drawGameOver.cpp
    src/plugPikiYamashita/drawHiScore.cpp
    src/plugPikiYamashita/drawHurryUp.cpp
    src/plugPikiYamashita/drawMenu.cpp
    src/plugPikiYamashita/drawMenuBase.cpp
    src/plugPikiYamashita/drawOptionSave.cpp
    src/plugPikiYamashita/drawProgre.cpp
    src/plugPikiYamashita/drawSaveFailure.cpp
    src/plugPikiYamashita/drawSaveMes.cpp
    src/plugPikiYamashita/drawUfoParts.cpp
    src/plugPikiYamashita/drawWMPause.cpp
    src/plugPikiYamashita/drawWorldMap.cpp
    src/plugPikiYamashita/effectMgr.cpp
    src/plugPikiYamashita/effectMgr2D.cpp
    src/plugPikiYamashita/gameCourseClear.cpp
    src/plugPikiYamashita/gameCredits.cpp
    src/plugPikiYamashita/gameStageClear.cpp
    src/plugPikiYamashita/menuPanelMgr.cpp
    src/plugPikiYamashita/P2DFont.cpp
    src/plugPikiYamashita/P2DGrafContext.cpp
    src/plugPikiYamashita/P2DOrthoGraph.cpp
    src/plugPikiYamashita/P2DPane.cpp
    src/plugPikiYamashita/P2DPerspGraph.cpp
    src/plugPikiYamashita/P2DPicture.cpp
    src/plugPikiYamashita/P2DPrint.cpp
    src/plugPikiYamashita/P2DScreen.cpp
    src/plugPikiYamashita/P2DStream.cpp
    src/plugPikiYamashita/P2DTextBox.cpp
    src/plugPikiYamashita/P2DWindow.cpp
    src/plugPikiYamashita/particleGenerator.cpp
    src/plugPikiYamashita/particleLoader.cpp
    src/plugPikiYamashita/particleManager.cpp
    src/plugPikiYamashita/particleMdlManager.cpp
    src/plugPikiYamashita/PSUList.cpp
    src/plugPikiYamashita/ptclGenPack.cpp
    src/plugPikiYamashita/PUTRect.cpp
    src/plugPikiYamashita/simpleParticle.cpp
    src/plugPikiYamashita/solidField.cpp
    src/plugPikiYamashita/spectrumCursorMgr.cpp
    src/plugPikiYamashita/TAIAattack.cpp
    src/plugPikiYamashita/TAIAeffect.cpp
    src/plugPikiYamashita/TAIAjudge.cpp
    src/plugPikiYamashita/TAIAmotion.cpp
    src/plugPikiYamashita/TAIAmove.cpp
    src/plugPikiYamashita/TAIanimation.cpp
    src/plugPikiYamashita/TAIAreaction.cpp
    src/plugPikiYamashita/TAIbeatle.cpp
    src/plugPikiYamashita/TAIdororo.cpp
    src/plugPikiYamashita/TAIeffectAttack.cpp
    src/plugPikiYamashita/TAIhibaA.cpp
    src/plugPikiYamashita/TAIkabekuiA.cpp
    src/plugPikiYamashita/TAIkabekuiB.cpp
    src/plugPikiYamashita/TAIkabekuiC.cpp
    src/plugPikiYamashita/TAImar.cpp
    src/plugPikiYamashita/TAImiurin.cpp
    src/plugPikiYamashita/TAIotama.cpp
    src/plugPikiYamashita/TAItamago.cpp
    src/plugPikiYamashita/TAItank.cpp
    src/plugPikiYamashita/TAIusuba.cpp
    src/plugPikiYamashita/tekiyamashita.cpp
    src/plugPikiYamashita/tekiyteki.cpp
    src/plugPikiYamashita/texAnim.cpp
    src/plugPikiYamashita/yai.cpp
    src/plugPikiYamashita/zenController.cpp
    src/plugPikiYamashita/zenGraphics.cpp
    src/plugPikiYamashita/zenMath.cpp
    src/plugPikiYamashita/zenSys.cpp
)

# set(SPROUT_FILES
#     src/sprout/main.cpp
# )
